# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Node.js CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   flatpak:
#     name: "FlatPak"
#     strategy:
#       matrix:
#           arch:
#             - x86_64
#             - aarch64
#           include:
#             - arch: x86_64
#               runner: ubuntu-latest
#             - arch: aarch64
#               runner: ubuntu-24.04-arm
        
#     runs-on: ${{ matrix.variant.runner }}

#     steps:
#       - uses: actions/checkout@v5
#       - name: setupnode
#         uses: actions/setup-node@v4.4.0
#         with:
#           node-version: 22.x
#       - run: npm ci
#       - run: npm run build
#       - run: npm run create-repo
        
